[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='my-xx-bucket'
folder='input'

[db]
host='df1649og1z5n.us-east-1.rds.amazonaws.com'
port=3306
database='superstore'
schema='superstore'
